<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userservice.proto

namespace Userservice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>userservice.AppDemo</code>
 */
class AppDemo extends \Google\Protobuf\Internal\Message
{
    protected $Request;

    public function __construct() {
        \GPBMetadata\Userservice::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.userservice.UserRequest userrequest = 1;</code>
     * @return \Userservice\UserRequest
     */
    public function getUserrequest()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.userservice.UserRequest userrequest = 1;</code>
     * @param \Userservice\UserRequest $var
     * @return $this
     */
    public function setUserrequest($var)
    {
        GPBUtil::checkMessage($var, \Userservice\UserRequest::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.userservice.UserResponse userresponse = 2;</code>
     * @return \Userservice\UserResponse
     */
    public function getUserresponse()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.userservice.UserResponse userresponse = 2;</code>
     * @param \Userservice\UserResponse $var
     * @return $this
     */
    public function setUserresponse($var)
    {
        GPBUtil::checkMessage($var, \Userservice\UserResponse::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.userservice.MixInfo mixinfo = 3;</code>
     * @return \Userservice\MixInfo
     */
    public function getMixinfo()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.userservice.MixInfo mixinfo = 3;</code>
     * @param \Userservice\MixInfo $var
     * @return $this
     */
    public function setMixinfo($var)
    {
        GPBUtil::checkMessage($var, \Userservice\MixInfo::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRequest()
    {
        return $this->whichOneof("Request");
    }

}

