<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userservice.proto

namespace Userservice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>userservice.MixInfo</code>
 */
class MixInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string username = 1;</code>
     */
    private $username = '';
    /**
     * Generated from protobuf field <code>string orgname = 2;</code>
     */
    private $orgname = '';
    /**
     * Generated from protobuf field <code>string orgid = 3;</code>
     */
    private $orgid = '';
    /**
     * Generated from protobuf field <code>string enterprise = 4;</code>
     */
    private $enterprise = '';
    /**
     * Generated from protobuf field <code>string enterpriseid = 5;</code>
     */
    private $enterpriseid = '';

    public function __construct() {
        \GPBMetadata\Userservice::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string username = 1;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string orgname = 2;</code>
     * @return string
     */
    public function getOrgname()
    {
        return $this->orgname;
    }

    /**
     * Generated from protobuf field <code>string orgname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOrgname($var)
    {
        GPBUtil::checkString($var, True);
        $this->orgname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string orgid = 3;</code>
     * @return string
     */
    public function getOrgid()
    {
        return $this->orgid;
    }

    /**
     * Generated from protobuf field <code>string orgid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOrgid($var)
    {
        GPBUtil::checkString($var, True);
        $this->orgid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string enterprise = 4;</code>
     * @return string
     */
    public function getEnterprise()
    {
        return $this->enterprise;
    }

    /**
     * Generated from protobuf field <code>string enterprise = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEnterprise($var)
    {
        GPBUtil::checkString($var, True);
        $this->enterprise = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string enterpriseid = 5;</code>
     * @return string
     */
    public function getEnterpriseid()
    {
        return $this->enterpriseid;
    }

    /**
     * Generated from protobuf field <code>string enterpriseid = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEnterpriseid($var)
    {
        GPBUtil::checkString($var, True);
        $this->enterpriseid = $var;

        return $this;
    }

}

