<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userservice.proto

namespace Userservice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>userservice.UserResponse</code>
 */
class UserResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     */
    private $code = 0;
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    private $message = '';
    /**
     * Generated from protobuf field <code>.userservice.MixInfo result = 3;</code>
     */
    private $result = null;

    public function __construct() {
        \GPBMetadata\Userservice::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.userservice.MixInfo result = 3;</code>
     * @return \Userservice\MixInfo
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.userservice.MixInfo result = 3;</code>
     * @param \Userservice\MixInfo $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \Userservice\MixInfo::class);
        $this->result = $var;

        return $this;
    }

}

